### ISSUE TITLE
(Emby) Media playing history doesnt display last played correctly

### ISSUE THREAD

**Issue by Sharnyaaa** [glanceapp/community-widgets#78]
### Widget link

https://github.com/glanceapp/community-widgets/blob/main/widgets/media-server-history-by-titembaatar/README.md

### Description

Hey there,

I just got this widget running with my emby server, its almost all working perfectly except the last played shows 55y ago when in relative or jan 1st in absolute

<img width="245" alt="Image" src="https://github.com/user-attachments/assets/5e08d188-2b76-47f4-84f4-2eec95cd0184" />

<img width="235" alt="Image" src="https://github.com/user-attachments/assets/49b100b1-b997-4631-bfa2-7e8973fc858c" />

**Comment by titembaatar** [comment]
Hi, for whatever reason Emby doesnt display the date in the API response, you need to specify that you need the field.

You'll need to add a parameter:
```yaml
  parameters:
    api_key: ${JELLYFIN_KEY}
    Limit: 10
    IncludeItemTypes: Movie,Episode, Audio
    Recursive: true
    isPlayed: true
    SortBy: DatePlayed
    SortOrder: Descending
    Fields: UserDataLastPlayedDate # Add this parameter
```

Please let me know if this resolves it.
